import { loadStripe } from "@stripe/stripe-js"
import { Inconsolata, Mukta } from "next/font/google"
import StripeProvider from "../app/providers/StripeProvider"
import SubscriptionModal from "./components/modals/SubscriptionModal"
import Navbar from "./components/navbar/Navbar"
import "./globals.css"
import ToastProvider from "./providers/ToastProvider"

import { Elements } from "@stripe/react-stripe-js"

const stripePromise = loadStripe(
  process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY!
)
const inconsolata = Inconsolata({ subsets: ["latin"] })
const mukta = Mukta({ weight: "500", subsets: ["latin"] })

export const metadata = {
  title: "Subscription App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inconsolata.className}>
        <header className={mukta.className}>
          <Navbar />
        </header>
        {/* <Elements stripe={stripePromise}> */}
        <StripeProvider stripePromise={stripePromise}>
          <SubscriptionModal />
        </StripeProvider>
        {/* </Elements> */}
        <ToastProvider />
        {children}
      </body>
    </html>
  )
}
