import { Inconsolata, Mukta } from "next/font/google"
import getCurrentUser from "./actions/getCurrentUser"
import LoginModal from "./components/modals/LoginModal"
import RegisterModal from "./components/modals/Registermodal"
import SubscriptionModal from "./components/modals/SubscriptionModal"
import Navbar from "./components/navbar/Navbar"
import "./globals.css"
import ThemeProvider from "./providers/ThemeProvider"
import ToastProvider from "./providers/ToastProvider"

const inconsolata = Inconsolata({ subsets: ["latin"] })
const mukta = Mukta({ weight: "500", subsets: ["latin"] })

export const metadata = {
  title: "Subscription App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()
  return (
    <html lang="en">
      <body className={inconsolata.className}>
        <ThemeProvider>
          <header className={mukta.className}>
            <Navbar currentUser={currentUser} />
          </header>
          <RegisterModal />
          <LoginModal />
          <SubscriptionModal />
          <ToastProvider />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
